### ISSUE TITLE
Installation failures debian 9

### ISSUE THREAD

**Issue by Bazmundi** [AISpace2/AISpace2#36]
During installation when I enter:

`jupyter nbextension install aispace2 --user --py`

The response is:

```
(jupyter) asterion@roam:~/python-projs$ jupyter nbextension install aispace2 --user --py
Traceback (most recent call last):
  File "/home/asterion/python-projs/jupyter/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/asterion/python-projs/jupyter/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named 'aispace2'

```

**Comment by Bazmundi** [comment]
In fact, I found running lab (and not notebook version) I was getting errors running lab cells.  I worked out using the --user for install of aispace2 on debian 9 was the problem.  I dropped the --user and the labs worked.  I haven't chased down why install of the extensions above was flaky, but first guess is the --user extension again (somehow).  I will investigate further when I can.
